apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: machine-config-daemon
  namespace: {{.TargetNamespace}}
spec:
  selector:
    matchLabels:
      k8s-app: machine-config-daemon
  template:
    metadata:
      name: machine-config-daemon
      labels:
        k8s-app: machine-config-daemon
    spec:
      containers:
      - name: machine-config-daemon
        image: {{.Images.MachineConfigDaemon}}
        args:
          - "start"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /rootfs
            name: rootfs
          - mountPath: /var/run/dbus
            name: var-run-dbus
          - mountPath: /run/systemd
            name: run-systemd
          - mountPath: /etc/ssl/certs
            name: etc-ssl-certs
            readOnly: true
          - mountPath: /etc/machine-config-daemon
            name: etc-mcd
            readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      hostNetwork: true
      hostPID: true
      serviceAccountName: machine-config-daemon
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run-dbus
          hostPath:
            path: /var/run/dbus
        - name: run-systemd
          hostPath:
            path: /run/systemd
        - name: etc-ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: etc-mcd
          hostPath:
            path: /etc/machine-config-daemon
